export const COUNTRY_META: Record<string, { name: string; currency: string; ibanLength: number }> = {
  AD: { name: 'Andorra', currency: 'EUR', ibanLength: 24 },
  AE: { name: 'United Arab Emirates', currency: 'AED', ibanLength: 23 },
  AL: { name: 'Albania', currency: 'ALL', ibanLength: 28 },
  AO: { name: 'Angola', currency: 'AOA', ibanLength: 25 },
  AT: { name: 'Austria', currency: 'EUR', ibanLength: 20 },
  AZ: { name: 'Azerbaijan', currency: 'AZN', ibanLength: 28 },
  BA: { name: 'Bosnia and Herzegovina', currency: 'BAM', ibanLength: 20 },
  BE: { name: 'Belgium', currency: 'EUR', ibanLength: 16 },
  BF: { name: 'Burkina Faso', currency: 'XOF', ibanLength: 28 },
  BG: { name: 'Bulgaria', currency: 'BGN', ibanLength: 22 },
  BH: { name: 'Bahrain', currency: 'BHD', ibanLength: 22 },
  BI: { name: 'Burundi', currency: 'BIF', ibanLength: 27 },
  BJ: { name: 'Benin', currency: 'XOF', ibanLength: 28 },
  BR: { name: 'Brazil', currency: 'BRL', ibanLength: 29 },
  CH: { name: 'Switzerland', currency: 'CHF', ibanLength: 21 },
  CI: { name: 'Côte d\'Ivoire', currency: 'XOF', ibanLength: 28 },
  CM: { name: 'Cameroon', currency: 'XAF', ibanLength: 27 },
  CR: { name: 'Costa Rica', currency: 'CRC', ibanLength: 22 },
  CV: { name: 'Cape Verde', currency: 'CVE', ibanLength: 25 },
  CY: { name: 'Cyprus', currency: 'EUR', ibanLength: 28 },
  CZ: { name: 'Czech Republic', currency: 'CZK', ibanLength: 24 },
  DE: { name: 'Germany', currency: 'EUR', ibanLength: 22 },
  DK: { name: 'Denmark', currency: 'DKK', ibanLength: 18 },
  DO: { name: 'Dominican Republic', currency: 'DOP', ibanLength: 28 },
  DZ: { name: 'Algeria', currency: 'DZD', ibanLength: 26 },
  EE: { name: 'Estonia', currency: 'EUR', ibanLength: 20 },
  EG: { name: 'Egypt', currency: 'EGP', ibanLength: 29 },
  ES: { name: 'Spain', currency: 'EUR', ibanLength: 24 },
  FI: { name: 'Finland', currency: 'EUR', ibanLength: 18 },
  FO: { name: 'Faroe Islands', currency: 'DKK', ibanLength: 18 },
  FR: { name: 'France', currency: 'EUR', ibanLength: 27 },
  GA: { name: 'Gabon', currency: 'XAF', ibanLength: 27 },
  GB: { name: 'United Kingdom', currency: 'GBP', ibanLength: 22 },
  GE: { name: 'Georgia', currency: 'GEL', ibanLength: 22 },
  GI: { name: 'Gibraltar', currency: 'GIP', ibanLength: 23 },
  GL: { name: 'Greenland', currency: 'DKK', ibanLength: 18 },
  GR: { name: 'Greece', currency: 'EUR', ibanLength: 27 },
  GT: { name: 'Guatemala', currency: 'GTQ', ibanLength: 28 },
  GW: { name: 'Guinea-Bissau', currency: 'XOF', ibanLength: 25 },
  HR: { name: 'Croatia', currency: 'EUR', ibanLength: 21 },
  HU: { name: 'Hungary', currency: 'HUF', ibanLength: 28 },
  IE: { name: 'Ireland', currency: 'EUR', ibanLength: 22 },
  IL: { name: 'Israel', currency: 'ILS', ibanLength: 23 },
  IQ: { name: 'Iraq', currency: 'IQD', ibanLength: 23 },
  IS: { name: 'Iceland', currency: 'ISK', ibanLength: 26 },
  IT: { name: 'Italy', currency: 'EUR', ibanLength: 27 },
  JO: { name: 'Jordan', currency: 'JOD', ibanLength: 30 },
  KW: { name: 'Kuwait', currency: 'KWD', ibanLength: 30 },
  KZ: { name: 'Kazakhstan', currency: 'KZT', ibanLength: 20 },
  LB: { name: 'Lebanon', currency: 'LBP', ibanLength: 28 },
  LC: { name: 'Saint Lucia', currency: 'XCD', ibanLength: 32 },
  LI: { name: 'Liechtenstein', currency: 'CHF', ibanLength: 21 },
  LT: { name: 'Lithuania', currency: 'EUR', ibanLength: 20 },
  LU: { name: 'Luxembourg', currency: 'EUR', ibanLength: 20 },
  LV: { name: 'Latvia', currency: 'EUR', ibanLength: 21 },
  LY: { name: 'Libya', currency: 'LYD', ibanLength: 25 },
  MA: { name: 'Morocco', currency: 'MAD', ibanLength: 28 },
  MC: { name: 'Monaco', currency: 'EUR', ibanLength: 27 },
  MD: { name: 'Moldova', currency: 'MDL', ibanLength: 24 },
  ME: { name: 'Montenegro', currency: 'EUR', ibanLength: 22 },
  MG: { name: 'Madagascar', currency: 'MGA', ibanLength: 27 },
  MK: { name: 'North Macedonia', currency: 'MKD', ibanLength: 19 },
  ML: { name: 'Mali', currency: 'XOF', ibanLength: 28 },
  MR: { name: 'Mauritania', currency: 'MRU', ibanLength: 27 },
  MT: { name: 'Malta', currency: 'EUR', ibanLength: 31 },
  MU: { name: 'Mauritius', currency: 'MUR', ibanLength: 30 },
  MZ: { name: 'Mozambique', currency: 'MZN', ibanLength: 25 },
  NE: { name: 'Niger', currency: 'XOF', ibanLength: 28 },
  NL: { name: 'Netherlands', currency: 'EUR', ibanLength: 18 },
  NO: { name: 'Norway', currency: 'NOK', ibanLength: 15 },
  PK: { name: 'Pakistan', currency: 'PKR', ibanLength: 24 },
  PL: { name: 'Poland', currency: 'PLN', ibanLength: 28 },
  PS: { name: 'Palestine', currency: 'ILS', ibanLength: 29 },
  PT: { name: 'Portugal', currency: 'EUR', ibanLength: 25 },
  QA: { name: 'Qatar', currency: 'QAR', ibanLength: 29 },
  RO: { name: 'Romania', currency: 'RON', ibanLength: 34 },
  RS: { name: 'Serbia', currency: 'RSD', ibanLength: 22 },
  RU: { name: 'Russia', currency: 'RUB', ibanLength: 33 }, // Note: IBAN usage limited; kept for structural validation
  SA: { name: 'Saudi Arabia', currency: 'SAR', ibanLength: 24 },
  SC: { name: 'Seychelles', currency: 'SCR', ibanLength: 31 },
  SD: { name: 'Sudan', currency: 'SDG', ibanLength: 18 },
  SE: { name: 'Sweden', currency: 'SEK', ibanLength: 24 },
  SI: { name: 'Slovenia', currency: 'EUR', ibanLength: 19 },
  SK: { name: 'Slovakia', currency: 'EUR', ibanLength: 24 },
  SM: { name: 'San Marino', currency: 'EUR', ibanLength: 27 },
  SN: { name: 'Senegal', currency: 'XOF', ibanLength: 28 },
  ST: { name: 'São Tomé and Príncipe', currency: 'STN', ibanLength: 25 },
  SV: { name: 'El Salvador', currency: 'USD', ibanLength: 28 },
  SY: { name: 'Syria', currency: 'SYP', ibanLength: 26 },
  TL: { name: 'Timor-Leste', currency: 'USD', ibanLength: 23 },
  TN: { name: 'Tunisia', currency: 'TND', ibanLength: 24 },
  TR: { name: 'Turkey', currency: 'TRY', ibanLength: 26 },
  UA: { name: 'Ukraine', currency: 'UAH', ibanLength: 29 },
  VA: { name: 'Vatican City', currency: 'EUR', ibanLength: 22 },
  VG: { name: 'British Virgin Islands', currency: 'USD', ibanLength: 24 },
  XK: { name: 'Kosovo', currency: 'EUR', ibanLength: 20 }
};